default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: datn_cmt_development

test:
  <<: *default
  database: datn_cmt_test

production:
  primary: &primary_production
    <<: *default
    database: datn_cmt_production
    username: datn_cmt
    password: <%= ENV["PAYFLOW_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: datn_cmt_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: datn_cmt_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: datn_cmt_production_cable
    migrations_paths: db/cable_migrate
