development:
  clients:
    default:
      uri: <%= Rails.application.credentials.dig(:development, :mongodb_uri) %>
      options:
        server_selection_timeout: 5
        connect_timeout: 5
        socket_timeout: 5
        max_pool_size: 5
        min_pool_size: 1

test:
  clients:
    default:
      uri: <%= Rails.application.credentials.dig(:development, :mongodb_uri) %>
      options:
        server_selection_timeout: 5
        connect_timeout: 5
        socket_timeout: 5
        max_pool_size: 5
        min_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
        connect_timeout: 5
        socket_timeout: 5
        max_pool_size: 5
        min_pool_size: 1
